sudo apt install -y \
accountsservice \
accountwizard \
acl \
acpica-tools \
adduser \
adwaita-icon-theme \
aesfix \
aeskeyfind \
afflib-tools \
akonadi-backend-mysql \
akonadi-server \
akregator \
alsa-utils \
anacron \
ant \
ant-optional \
anthy \
anthy-common \
apache2-bin \
apg \
apper \
apper-data \
appstream \
apt \
apt-file \
apt-listchanges \
apt-utils \
argyll \
argyll-ref \
ark \
aspell \
aspell-en \
at-spi2-core \
attr \
augeas-lenses \
augeas-tools \
autoconf \
automake \
autotools-dev \
avahi-autoipd \
avahi-daemon \
awscli \
baloo-kf5 \
baobab \
base-files \
base-passwd \
bash \
bash-completion \
bc \
bcc \
bdf2psf \
bin86 \
bind9-host \
binfmt-support \
binutils \
bison \
bluedevil \
bluetooth \
bluez \
bluez-obexd \
bogofilter \
bogofilter-bdb \
bogofilter-common \
brasero \
brasero-cdrkit \
brasero-common \
breeze \
breeze-cursor-theme \
breeze-icon-theme \
bridge-utils \
bruteforce-salted-openssl \
bsdmainutils \
bsdutils \
btrfs-progs \
btrfs-tools \
build-essential \
busybox \
bzip2 \
bzip2-doc \
ca-certificates \
ca-certificates-java \
ca-certificates-mono \
cabextract \
camlp4 \
caribou \
catdoc \
cdparanoia \
cdrdao \
cewl \
chaosreader \
check \
cheese \
cheese-common \
chrome-gnome-shell \
cli-common \
cmake \
cmake-data \
coinor-libcbc3 \
coinor-libcgl1 \
coinor-libclp1 \
coinor-libcoinmp1v5 \
coinor-libcoinutils3v5 \
coinor-libosi1v5 \
colord \
colord-data \
comerr-dev \
console-setup \
console-setup-linux \
coreutils \
cpio \
cpp \
cpp-6 \
crack-common \
crack-md5 \
cracklib-runtime \
crash \
crda \
cron \
cryptsetup \
cryptsetup-bin \
cups \
cups-browsed \
cups-bsd \
cups-client \
cups-common \
cups-core-drivers \
cups-daemon \
cups-filters \
cups-filters-core-drivers \
cups-pk-helper \
cups-ppdc \
cups-server-common \
curl \
dash \
db-util \
db5.3-util \
dbus \
dbus-user-session \
dbus-x11 \
dc \
dc3dd \
dconf-cli \
dconf-gsettings-backend \
dconf-service \
dcraw \
debconf \
debconf-i18n \
debconf-kde-data \
debconf-kde-helper \
debian-archive-keyring \
debian-faq \
debianutils \
debootstrap \
debugedit \
default-java-plugin \
default-jre \
default-jre-headless \
default-mysql-server \
desktop-base \
desktop-file-utils \
dh-python \
dictionaries-common \
diffutils \
discover \
discover-data \
dislocker \
distro-info-data \
dkms \
dleyna-server \
dmeventd \
dmidecode \
dmsetup \
dns-root-data \
dnsmasq-base \
doc-debian \
docbook-xml \
docbook-xsl \
docutils-common \
dolphin \
dolphin4 \
dosfstools \
dpdk \
dpkg \
dpkg-dev \
dragonplayer \
dvd+rw-tools \
dvdauthor \
dwarfdump \
e17 \
e17-data \
e2fslibs \
e2fslibs-dev \
e2fsprogs \
ebtables \
ed2k-hash \
eject \
elks-libc \
emacsen-common \
enchant \
eog \
espeak-ng-data \
ethtool \
evince \
evince-common \
evolution \
evolution-common \
evolution-data-server \
evolution-data-server-common \
evolution-plugins \
ewf-tools \
exfat-fuse \
exfat-utils \
exif \
exifprobe \
exim4-base \
exim4-config \
exim4-daemon-light \
ext3grep \
ext4magic \
extlinux \
extundelete \
fakeroot \
fbterm \
fcrackzip \
festival \
festival-freebsoft-utils \
festlex-cmu \
festlex-poslex \
festvox-kallpc16k \
fig2dev \
file \
file-roller \
findutils \
firefox-esr \
firefox-esr-l10n-ja \
five-or-more \
flac \
flex \
folks-common \
fontconfig \
fontconfig-config \
fonts-cantarell \
fonts-crosextra-caladea \
fonts-crosextra-carlito \
fonts-dejavu \
fonts-dejavu-core \
fonts-dejavu-extra \
fonts-droid-fallback \
fonts-hack-ttf \
fonts-ipafont \
fonts-ipafont-gothic \
fonts-ipafont-mincho \
fonts-lato \
fonts-liberation \
fonts-linuxlibertine \
fonts-noto \
fonts-noto-cjk \
fonts-noto-hinted \
fonts-noto-mono \
fonts-noto-unhinted \
fonts-opensymbol \
fonts-oxygen \
fonts-sil-gentium \
fonts-sil-gentium-basic \
fonts-vlgothic \
foomatic-db-compressed-ppds \
foomatic-db-engine \
forensic-artifacts \
forensics-all \
forensics-colorize \
four-in-a-row \
frameworkintegration \
freepats \
fuse \
g++ \
g++-6 \
galera-3 \
galleta \
gawk \
gcc \
gcc-6 \
gcc-6-base \
gcc-6-multilib \
gcc-multilib \
gcj-6-jre-lib \
gconf-service \
gconf2 \
gconf2-common \
gcr \
gdb \
gdisk \
gdm3 \
gedit \
gedit-common \
gedit-plugins \
genisoimage \
geoclue-2.0 \
geoip-database \
gettext \
gettext-base \
ghc \
ghostscript \
gimp \
gimp-data \
gir1.2-accountsservice-1.0 \
gir1.2-atk-1.0 \
gir1.2-atspi-2.0 \
gir1.2-caribou-1.0 \
gir1.2-champlain-0.12 \
gir1.2-clutter-1.0 \
gir1.2-clutter-gst-3.0 \
gir1.2-cogl-1.0 \
gir1.2-coglpango-1.0 \
gir1.2-evince-3.0 \
gir1.2-freedesktop \
gir1.2-gck-1 \
gir1.2-gcr-3 \
gir1.2-gdata-0.0 \
gir1.2-gdesktopenums-3.0 \
gir1.2-gdkpixbuf-2.0 \
gir1.2-gdm-1.0 \
gir1.2-geoclue-2.0 \
gir1.2-geocodeglib-1.0 \
gir1.2-gepub-0.4 \
gir1.2-gfbgraph-0.2 \
gir1.2-git2-glib-1.0 \
gir1.2-glib-2.0 \
gir1.2-gmenu-3.0 \
gir1.2-gnomebluetooth-1.0 \
gir1.2-gnomedesktop-3.0 \
gir1.2-gnomekeyring-1.0 \
gir1.2-goa-1.0 \
gir1.2-grilo-0.3 \
gir1.2-gst-plugins-base-1.0 \
gir1.2-gstreamer-1.0 \
gir1.2-gtk-3.0 \
gir1.2-gtk-vnc-2.0 \
gir1.2-gtkchamplain-0.12 \
gir1.2-gtkclutter-1.0 \
gir1.2-gtksource-3.0 \
gir1.2-gucharmap-2.90 \
gir1.2-gweather-3.0 \
gir1.2-ibus-1.0 \
gir1.2-javascriptcoregtk-4.0 \
gir1.2-json-1.0 \
gir1.2-libosinfo-1.0 \
gir1.2-libvirt-glib-1.0 \
gir1.2-lokdocview-0.1 \
gir1.2-mediaart-2.0 \
gir1.2-mutter-3.0 \
gir1.2-networkmanager-1.0 \
gir1.2-nmgtk-1.0 \
gir1.2-notify-0.7 \
gir1.2-packagekitglib-1.0 \
gir1.2-pango-1.0 \
gir1.2-peas-1.0 \
gir1.2-polkit-1.0 \
gir1.2-rb-3.0 \
gir1.2-rest-0.7 \
gir1.2-secret-1 \
gir1.2-soup-2.4 \
gir1.2-spice-client-glib-2.0 \
gir1.2-spice-client-gtk-3.0 \
gir1.2-telepathyglib-0.12 \
gir1.2-telepathylogger-0.2 \
gir1.2-totem-1.0 \
gir1.2-totem-plparser-1.0 \
gir1.2-tracker-1.0 \
gir1.2-upowerglib-1.0 \
gir1.2-vte-2.91 \
gir1.2-webkit2-4.0 \
gir1.2-wnck-3.0 \
gir1.2-zeitgeist-2.0 \
gir1.2-zpj-0.0 \
git \
git-core \
git-man \
gjs \
gkbd-capplet \
gksu \
glib-networking \
glib-networking-common \
glib-networking-services \
gnome \
gnome-accessibility-themes \
gnome-backgrounds \
gnome-bluetooth \
gnome-calculator \
gnome-calendar \
gnome-characters \
gnome-chess \
gnome-clocks \
gnome-color-manager \
gnome-contacts \
gnome-control-center \
gnome-control-center-data \
gnome-core \
gnome-desktop3-data \
gnome-dictionary \
gnome-disk-utility \
gnome-documents \
gnome-font-viewer \
gnome-games \
gnome-getting-started-docs \
gnome-icon-theme \
gnome-keyring \
gnome-klotski \
gnome-logs \
gnome-mahjongg \
gnome-maps \
gnome-menus \
gnome-mines \
gnome-music \
gnome-nibbles \
gnome-online-accounts \
gnome-online-miners \
gnome-orca \
gnome-robots \
gnome-screenshot \
gnome-session \
gnome-session-bin \
gnome-session-common \
gnome-settings-daemon \
gnome-shell \
gnome-shell-common \
gnome-shell-extensions \
gnome-software \
gnome-software-common \
gnome-sound-recorder \
gnome-sudoku \
gnome-sushi \
gnome-system-monitor \
gnome-taquin \
gnome-terminal \
gnome-terminal-data \
gnome-tetravex \
gnome-themes-standard \
gnome-themes-standard-data \
gnome-tweak-tool \
gnome-user-guide \
gnome-user-share \
gnome-video-effects \
gnome-weather \
gnupg \
gnupg-agent \
gnupg2 \
gnustep-base-common \
gnustep-base-runtime \
gnustep-common \
golang \
golang-1.7 \
golang-1.7-doc \
golang-1.7-go \
golang-1.7-src \
golang-doc \
golang-go \
golang-src \
gpart \
gpgv \
grep \
grilo-plugins-0.3 \
groff-base \
grokevt \
growisofs \
grub-common \
grub-pc \
grub-pc-bin \
grub-xen-bin \
grub-xen-host \
grub2-common \
gsettings-desktop-schemas \
gsfonts \
gstreamer1.0-clutter-3.0 \
gstreamer1.0-libav \
gstreamer1.0-plugins-bad \
gstreamer1.0-plugins-base \
gstreamer1.0-plugins-good \
gstreamer1.0-plugins-ugly \
gstreamer1.0-pulseaudio \
gstreamer1.0-x \
gtk-update-icon-cache \
gtk2-engines-pixbuf \
gtk3-engines-breeze \
guake \
guile-2.0-libs \
guymager \
gvfs \
gvfs-backends \
gvfs-bin \
gvfs-common \
gvfs-daemons \
gvfs-fuse \
gvfs-libs \
gwenview \
gzip \
hashdeep \
hashrat \
hdparm \
hfsplus \
hicolor-icon-theme \
hitori \
hoichess \
hostname \
hp-ppd \
hplip \
hplip-data \
hunspell-en-us \
hwdata \
hyphen-en-us \
i965-va-driver \
iagno \
icedove \
icedove-l10n-ja \
icedtea-8-plugin \
icedtea-netx \
icedtea-netx-common \
icoutils \
icu-devtools \
ieee-data \
ifupdown \
iio-sensor-proxy \
im-config \
imagemagick \
imagemagick-6-common \
imagemagick-6.q16 \
init \
init-system-helpers \
initramfs-tools \
initramfs-tools-core \
inkscape \
install-info \
installation-report \
iproute \
iproute2 \
iptables \
iputils-arping \
iputils-ping \
ipxe-qemu \
ipython \
isc-dhcp-client \
isc-dhcp-common \
iso-codes \
iw \
java-common \
javascript-common \
jovie \
juk \
k3b \
k3b-data \
k3b-i18n \
kaccessible \
kaccounts-providers \
kactivities-bin \
kactivitymanagerd \
kaddressbook \
kamera \
kasumi \
kate \
kate-data \
kate5-data \
katepart \
kbd \
kcalc \
kde-baseapps \
kde-baseapps-bin \
kde-baseapps-data \
kde-cli-tools \
kde-cli-tools-data \
kde-config-gtk-style \
kde-config-mailtransport \
kde-config-screenlocker \
kde-config-sddm \
kde-icons-mono \
kde-plasma-desktop \
kde-runtime \
kde-runtime-data \
kde-spectacle \
kde-standard \
kde-style-breeze \
kde-style-breeze-qt4 \
kde-style-oxygen-qt5 \
kde-style-qtcurve-qt4 \
kde-style-qtcurve-qt5 \
kdeaccessibility \
kdeconnect \
kded5 \
kdelibs-bin \
kdelibs5-data \
kdelibs5-plugins \
kdepasswd \
kdepim-addons \
kdepim-doc \
kdepim-runtime \
kdepim-themeeditors \
kdepimlibs-data \
kdeplasma-addons-data \
kdesudo \
kdoctools \
kdoctools5 \
keyboard-configuration \
kf5-kdepim-apps-libs-data \
kf5-kdepimlibs-kio-plugins \
kf5-messagelib-data \
kfind \
kgamma5 \
khelpcenter \
khotkeys \
khotkeys-data \
kinfocenter \
kinit \
kio \
kio-extras \
kio-extras-data \
klibc-utils \
kmag \
kmail \
kmenuedit \
kmod \
kmousetool \
kmouth \
knotes \
konq-plugins \
konqueror \
konqueror-nsplugins \
konsole \
konsole-kpart \
kopete \
korganizer \
kpackagelauncherqml \
kpackagetool5 \
kpart-webkit \
krb5-locales \
krb5-multidev \
kross \
kscreen \
ksshaskpass \
ksysguard \
ksysguard-data \
ksysguardd \
ktexteditor-data \
ktexteditor-katepart \
ktnef \
kwalletmanager \
kwin-common \
kwin-data \
kwin-style-breeze \
kwin-x11 \
kwrite \
kwrited \
laptop-detect \
ldmtool \
ledit \
less \
lib32asan3 \
lib32atomic1 \
lib32cilkrts5 \
lib32gcc-6-dev \
lib32gcc1 \
lib32gomp1 \
lib32itm1 \
lib32mpx2 \
lib32quadmath0 \
lib32stdc++6 \
lib32ubsan0 \
liba52-0.7.4 \
libaa1 \
libaacs0 \
libabw-0.1-1 \
libaccounts-glib0 \
libaccounts-qt5-1 \
libaccountsservice0 \
libacl1 \
libafflib0v5 \
libaio-dev \
libaio1 \
libalgorithm-diff-perl \
libalgorithm-diff-xs-perl \
libalgorithm-merge-perl \
libamd2 \
libanthy0 \
libao-common \
libao4 \
libapache-poi-java \
libapache-pom-java \
libapache2-mod-dnssd \
libapparmor1 \
libappstream-glib8 \
libappstream4 \
libappstreamqt2 \
libapr1 \
libaprutil1 \
libaprutil1-dbd-sqlite3 \
libaprutil1-ldap \
libapt-inst2.0 \
libapt-pkg-perl \
libapt-pkg5.0 \
libarchive13 \
libart-2.0-2 \
libasan3 \
libasound2 \
libasound2-data \
libasound2-dev \
libasound2-plugins \
libaspell15 \
libass5 \
libassuan0 \
libasyncns0 \
libatasmart4 \
libatk-adaptor \
libatk-bridge2.0-0 \
libatk-wrapper-java \
libatk-wrapper-java-jni \
libatk1.0-0 \
libatk1.0-data \
libatkmm-1.6-1v5 \
libatomic1 \
libatspi2.0-0 \
libattica0.4 \
libattr1 \
libaudio2 \
libaudit-common \
libaudit1 \
libaugeas0 \
libauthen-sasl-perl \
libavahi-client3 \
libavahi-common-data \
libavahi-common3 \
libavahi-core7 \
libavahi-glib1 \
libavahi-gobject0 \
libavahi-ui-gtk3-0 \
libavc1394-0 \
libavcodec57 \
libavfilter6 \
libavformat57 \
libavresample3 \
libavutil55 \
libbabeltrace-ctf1 \
libbabeltrace1 \
libbabl-0.1-0 \
libbase-java \
libbasicusageenvironment1 \
libbcmail-java \
libbcpkix-java \
libbcprov-java \
libbde1 \
libbdplus0 \
libbfio1 \
libbind9-140 \
libbison-dev \
libblas-common \
libblas3 \
libblkid1 \
libbluetooth3 \
libbluray1 \
libboost-date-time1.62.0 \
libboost-filesystem1.62.0 \
libboost-iostreams1.62.0 \
libboost-random1.62.0 \
libboost-system1.62.0 \
libboost-thread1.62.0 \
libbrasero-media3-1 \
libbrlapi0.6 \
libbs2b0 \
libbsd-dev \
libbsd0 \
libbsh-java \
libburn4 \
libbz2-1.0 \
libbz2-dev \
libc-bin \
libc-dev-bin \
libc-l10n \
libc6 \
libc6-dbg \
libc6-dev \
libc6-dev-i386 \
libc6-dev-x32 \
libc6-i386 \
libc6-x32 \
libcaca-dev \
libcaca0 \
libcacard0 \
libcairo-gobject2 \
libcairo-perl \
libcairo2 \
libcairomm-1.0-1v5 \
libcamd2 \
libcamel-1.2-59 \
libcamlp4-ocaml-dev \
libcanberra-gtk3-0 \
libcanberra-gtk3-module \
libcanberra-pulse \
libcanberra0 \
libcap-ng0 \
libcap2 \
libcap2-bin \
libcapstone3 \
libcaribou-common \
libcaribou-gtk-module \
libcaribou-gtk3-module \
libcaribou0 \
libcc1-0 \
libccolamd2 \
libcddb2 \
libcdio-cdda1 \
libcdio-paranoia1 \
libcdio13 \
libcdparanoia0 \
libcdr-0.1-1 \
libcgi-fast-perl \
libcgi-pm-perl \
libchamplain-0.12-0 \
libchamplain-gtk-0.12-0 \
libcheese-gtk25 \
libcheese8 \
libcholmod3 \
libchromaprint1 \
libcilkrts5 \
libclass-isa-perl \
libcln6 \
libclucene-contribs1v5 \
libclucene-core1v5 \
libclutter-1.0-0 \
libclutter-1.0-common \
libclutter-gst-3.0-0 \
libclutter-gtk-1.0-0 \
libcmis-0.5-5v5 \
libcogl-common \
libcogl-pango20 \
libcogl-path20 \
libcogl20 \
libcolamd2 \
libcolord-gtk1 \
libcolord2 \
libcolorhug2 \
libcomerr2 \
libcommons-codec-java \
libcommons-collections3-java \
libcommons-logging-java \
libcommons-parent-java \
libconfig-inifiles-perl \
libconfig9 \
libcrack2 \
libcroco3 \
libcryptsetup4 \
libcryptui0a \
libcrystalhd3 \
libcue1 \
libcups2 \
libcupscgi1 \
libcupsfilters1 \
libcupsimage2 \
libcupsmime1 \
libcupsppdc1 \
libcurl3 \
libcurl3-gnutls \
libcurl4-openssl-dev \
libdaemon0 \
libdata-validate-domain-perl \
libdata-validate-ip-perl \
libdata-validate-uri-perl \
libdate-manip-perl \
libdatrie1 \
libdb5.3 \
libdbd-mysql-perl \
libdbi-perl \
libdbus-1-3 \
libdbus-glib-1-2 \
libdbus-glib2.0-cil \
libdbus-glib2.0-cil-dev \
libdbus2.0-cil \
libdbus2.0-cil-dev \
libdbusmenu-qt2 \
libdbusmenu-qt5-2 \
libdc1394-22 \
libdca0 \
libdconf1 \
libde265-0 \
libdebconf-kde1 \
libdebconfclient0 \
libdee-1.0-4 \
libdevmapper-dev \
libdevmapper-event1.02.1 \
libdevmapper1.02.1 \
libdiscover2 \
libdislocker0.6 \
libdistorm3-3 \
libdjvulibre-text \
libdjvulibre21 \
libdleyna-connector-dbus-1.0-1 \
libdleyna-core-1.0-3 \
libdlrestrictions1 \
libdmapsharing-3.0-2 \
libdns-export162 \
libdns162 \
libdolphinvcs5 \
libdom4j-java \
libdotconf0 \
libdouble-conversion1 \
libdpkg-perl \
libdrm-amdgpu1 \
libdrm-dev \
libdrm-intel1 \
libdrm-nouveau2 \
libdrm-radeon1 \
libdrm2 \
libdv4 \
libdvbpsi10 \
libdvdnav4 \
libdvdread4 \
libdw1 \
libe-book-0.1-1 \
libebackend-1.2-10 \
libebml4v5 \
libebook-1.2-16 \
libebook-contacts-1.2-2 \
libebur128-1 \
libecal-1.2-19 \
libecore-con1 \
libecore-evas1 \
libecore-fb1 \
libecore-file1 \
libecore-imf1 \
libecore-input1 \
libecore-ipc1 \
libecore-x1 \
libecore1 \
libedata-book-1.2-25 \
libedata-cal-1.2-28 \
libedataserver-1.2-22 \
libedataserverui-1.2-1 \
libedbus1 \
libedit2 \
libedje-bin \
libedje1 \
libeet1 \
libeeze1 \
libefreet-bin \
libefreet1a \
libegl1-mesa \
libehcache-java \
libeina1 \
libeio1 \
libelf1 \
libembryo-bin \
libembryo1 \
libenca0 \
libenchant1c2a \
libencode-locale-perl \
libeot0 \
libepoxy0 \
libept1.5.0 \
libepub0 \
liberror-perl \
libesedb1 \
libespeak-ng1 \
libestools2.4 \
libestr0 \
libetonyek-0.1-1 \
libevas-loaders \
libevas1 \
libevas1-engines-x \
libevdev2 \
libevdocument3-4 \
libevent-2.0-5 \
libevolution \
libevt1 \
libevtx1 \
libevview3-3 \
libewf2 \
libexempi3 \
libexif12 \
libexiv2-14 \
libexpat1 \
libexpat1-dev \
libexpect-perl \
libexporter-tiny-perl \
libexttextcat-2.0-0 \
libexttextcat-data \
libfaad2 \
libfakekey0 \
libfakeroot \
libfam0 \
libfastjson4 \
libfcgi-perl \
libfdisk1 \
libfdt-dev \
libfdt1 \
libffi-dev \
libffi6 \
libfftw3-double3 \
libfftw3-single3 \
libfile-basedir-perl \
libfile-copy-recursive-perl \
libfile-desktopentry-perl \
libfile-fcntllock-perl \
libfile-listing-perl \
libfile-mimeinfo-perl \
libfile-slurp-perl \
libfile-which-perl \
libfindlib-ocaml \
libfindlib-ocaml-dev \
libfl-dev \
libflac++6v5 \
libflac8 \
libflite1 \
libfluidsynth1 \
libflute-java \
libfolks-eds25 \
libfolks-telepathy25 \
libfolks25 \
libfont-afm-perl \
libfontconfig1 \
libfontembed1 \
libfontenc1 \
libfonts-java \
libformula-java \
libfreehand-0.1-1 \
libfreerdp-cache1.1 \
libfreerdp-codec1.1 \
libfreerdp-common1.1.0 \
libfreerdp-core1.1 \
libfreerdp-crypto1.1 \
libfreerdp-gdi1.1 \
libfreerdp-locale1.1 \
libfreerdp-primitives1.1 \
libfreerdp-utils1.1 \
libfreetype6 \
libfribidi0 \
libfsntfs1 \
libfuse-dev \
libfuse2 \
libfvde1 \
libfwnt1 \
libfwsi1 \
libfwupd1 \
libgadu3 \
libgail-3-0 \
libgail-common \
libgail18 \
libgbm1 \
libgc1c2 \
libgcab-1.0-0 \
libgcc-6-dev \
libgcc1 \
libgcj-bc \
libgcj-common \
libgcj17 \
libgck-1-0 \
libgconf-2-4 \
libgcr-3-common \
libgcr-base-3-1 \
libgcr-ui-3-1 \
libgcroots0 \
libgcrypt20 \
libgd3 \
libgdata-common \
libgdata22 \
libgdbm-dev \
libgdbm3 \
libgdict-1.0-10 \
libgdict-common \
libgdk-pixbuf2.0-0 \
libgdk-pixbuf2.0-common \
libgdm1 \
libgee-0.8-2 \
libgegl-0.3-0 \
libgeoclue-2-0 \
libgeocode-glib0 \
libgeoip1 \
libgepub0 \
libgexiv2-2 \
libgfbgraph-0.2-0 \
libgfortran3 \
libgif7 \
libgimp2.0 \
libgirepository-1.0-1 \
libgit2-24 \
libgit2-glib-1.0-0 \
libgjs0e \
libgksu2-0 \
libgl1-mesa-dev \
libgl1-mesa-dri \
libgl1-mesa-glx \
libglade2-0 \
libglapi-mesa \
libgles2-mesa \
libglew2.0 \
libglib-perl \
libglib2.0-0 \
libglib2.0-0-dbg \
libglib2.0-bin \
libglib2.0-cil \
libglib2.0-cil-dev \
libglib2.0-data \
libglib2.0-dev \
libglib2.0-doc \
libglib2.0-tests \
libglibmm-2.4-1v5 \
libgltf-0.0-0v5 \
libglu1-mesa \
libglu1-mesa-dev \
libgme0 \
libgmime-2.6-0 \
libgmp-dev \
libgmp10 \
libgmpxx4ldbl \
libgnome-autoar-0-0 \
libgnome-autoar-common \
libgnome-autoar-gtk-0-0 \
libgnome-bluetooth13 \
libgnome-desktop-3-12 \
libgnome-games-support-1-2 \
libgnome-games-support-common \
libgnome-keyring-common \
libgnome-keyring0 \
libgnome-menu-3-0 \
libgnomekbd-common \
libgnomekbd8 \
libgnustep-base1.24 \
libgnutls-dane0 \
libgnutls-openssl27 \
libgnutls28-dev \
libgnutls30 \
libgnutlsxx28 \
libgoa-1.0-0b \
libgoa-1.0-common \
libgoa-backend-1.0-1 \
libgom-1.0-0 \
libgom-1.0-common \
libgomp1 \
libgovirt-common \
libgovirt2 \
libgpg-error0 \
libgpgme++2v5 \
libgpgme11 \
libgpgmepp6 \
libgphoto2-6 \
libgphoto2-l10n \
libgphoto2-port12 \
libgpm2 \
libgpod-common \
libgpod4 \
libgps22 \
libgrantlee-templates5 \
libgrantlee-textdocument5 \
libgraphite2-3 \
libgrilo-0.3-0 \
libgroupsock8 \
libgs9 \
libgs9-common \
libgsasl7 \
libgsasl7-dev \
libgsf-1-114 \
libgsf-1-common \
libgsf-bin \
libgsl2 \
libgsm1 \
libgsound0 \
libgspell-1-1 \
libgspell-1-common \
libgssapi-krb5-2 \
libgssdp-1.0-3 \
libgssrpc4 \
libgstreamer-plugins-bad1.0-0 \
libgstreamer-plugins-base1.0-0 \
libgstreamer1.0-0 \
libgtk-3-0 \
libgtk-3-bin \
libgtk-3-common \
libgtk-vnc-1.0-0 \
libgtk-vnc-2.0-0 \
libgtk2-perl \
libgtk2.0-0 \
libgtk2.0-bin \
libgtk2.0-common \
libgtkmm-2.4-1v5 \
libgtkmm-3.0-1v5 \
libgtksourceview-3.0-1 \
libgtksourceview-3.0-common \
libgtkspell0 \
libgtkspell3-3-0 \
libgtop-2.0-10 \
libgtop2-common \
libgucharmap-2-90-7 \
libgudev-1.0-0 \
libguestfs-hfsplus \
libguestfs-perl \
libguestfs-reiserfs \
libguestfs-tools \
libguestfs-xfs \
libguestfs0 \
libgupnp-1.0-4 \
libgupnp-av-1.0-2 \
libgupnp-dlna-2.0-3 \
libgusb2 \
libgutenprint2 \
libguytools2 \
libgvnc-1.0-0 \
libgweather-3-6 \
libgweather-common \
libgxps2 \
libharfbuzz-icu0 \
libharfbuzz0b \
libhfsp0 \
libhivex0 \
libhogweed4 \
libhpmud0 \
libhsqldb1.8.0-java \
libhtml-form-perl \
libhtml-format-perl \
libhtml-parser-perl \
libhtml-tagset-perl \
libhtml-template-perl \
libhtml-tree-perl \
libhttp-cookies-perl \
libhttp-daemon-perl \
libhttp-date-perl \
libhttp-message-perl \
libhttp-negotiate-perl \
libhttp-parser2.1 \
libhunspell-1.4-0 \
libhyphen0 \
libibus-1.0-5 \
libical2 \
libice6 \
libicu-dev \
libicu57 \
libidn11 \
libidn11-dev \
libidn2-0 \
libiec61883-0 \
libieee1284-3 \
libijs-0.35 \
libilmbase12 \
libimage-magick-perl \
libimage-magick-q16-perl \
libimobiledevice6 \
libinput-bin \
libinput10 \
libintl-perl \
libintl-xs-perl \
libio-html-perl \
libio-pty-perl \
libio-socket-ssl-perl \
libio-stty-perl \
libiodbc2 \
libip4tc0 \
libip6tc0 \
libipc-system-simple-perl \
libiptc0 \
libiptcdata0 \
libisc-export160 \
libisc160 \
libisccc140 \
libisccfg140 \
libisl15 \
libiso9660-8 \
libisofs6 \
libisorelax-java \
libitext-java \
libitm1 \
libiw30 \
libjack-jackd2-0 \
libjansson-dev \
libjansson4 \
libjavascriptcoregtk-4.0-18 \
libjaxen-java \
libjbig0 \
libjbig2dec0 \
libjcommon-java \
libjdom1-java \
libjemalloc1 \
libjim0.76 \
libjpeg-dev \
libjpeg-turbo-progs \
libjpeg62-turbo \
libjpeg62-turbo-dev \
libjs-jquery \
libjs-sphinxdoc \
libjs-underscore \
libjson-c-dev \
libjson-c3 \
libjson-glib-1.0-0 \
libjson-glib-1.0-common \
libjsoncpp1 \
libjte1 \
libjxr-tools \
libjxr0 \
libk3b6 \
libk3b6-extracodecs \
libk5crypto3 \
libkabc4 \
libkaccounts1 \
libkactivities6 \
libkadm5clnt-mit11 \
libkadm5srv-mit11 \
libkate1 \
libkatepartinterfaces4 \
libkcddb4 \
libkcmutils4 \
libkcompactdisc4 \
libkdb5-8 \
libkde3support4 \
libkdeclarative5 \
libkdecorations2-5v5 \
libkdecorations2private5v5 \
libkdecore5 \
libkdesu5 \
libkdeui5 \
libkdewebkit5 \
libkdnssd4 \
libkemoticons4 \
libkexiv2-11 \
libkexiv2-data \
libkeybinder0 \
libkeyutils1 \
libkf5activities5 \
libkf5activitiesstats1 \
libkf5akonadiagentbase5 \
libkf5akonadicalendar5 \
libkf5akonadicontact5 \
libkf5akonadicore-bin \
libkf5akonadicore5 \
libkf5akonadimime5 \
libkf5akonadinotes5 \
libkf5akonadiprivate5 \
libkf5akonadisearch-bin \
libkf5akonadisearch-data \
libkf5akonadisearch-plugins \
libkf5akonadisearchcore5 \
libkf5akonadisearchdebug5 \
libkf5akonadisearchpim5 \
libkf5akonadisearchxapian5 \
libkf5akonadiwidgets5 \
libkf5alarmcalendar5 \
libkf5archive5 \
libkf5attica5 \
libkf5auth-data \
libkf5auth5 \
libkf5baloo5 \
libkf5balooengine5 \
libkf5baloowidgets-bin \
libkf5baloowidgets5 \
libkf5bluezqt-data \
libkf5bluezqt6 \
libkf5bookmarks-data \
libkf5bookmarks5 \
libkf5calendarcore5 \
libkf5calendarevents5 \
libkf5calendarsupport-data \
libkf5calendarsupport5 \
libkf5calendarutils5 \
libkf5codecs-data \
libkf5codecs5 \
libkf5completion-data \
libkf5completion5 \
libkf5config-bin \
libkf5config-data \
libkf5configcore5 \
libkf5configgui5 \
libkf5configwidgets-data \
libkf5configwidgets5 \
libkf5contacts-data \
libkf5contacts5 \
libkf5coreaddons-data \
libkf5coreaddons5 \
libkf5crash5 \
libkf5dbusaddons-bin \
libkf5dbusaddons-data \
libkf5dbusaddons5 \
libkf5declarative-data \
libkf5declarative5 \
libkf5dnssd-data \
libkf5dnssd5 \
libkf5emoticons-bin \
libkf5emoticons-data \
libkf5emoticons5 \
libkf5eventviews-data \
libkf5eventviews5 \
libkf5filemetadata-bin \
libkf5filemetadata-data \
libkf5filemetadata3 \
libkf5followupreminder5 \
libkf5gapi-data \
libkf5gapicalendar5 \
libkf5gapicontacts5 \
libkf5gapicore5 \
libkf5gapitasks5 \
libkf5globalaccel-bin \
libkf5globalaccel-data \
libkf5globalaccel5 \
libkf5globalaccelprivate5 \
libkf5gpgmepp-pthread5 \
libkf5grantleetheme-plugins \
libkf5grantleetheme5 \
libkf5gravatar5 \
libkf5guiaddons5 \
libkf5holidays-data \
libkf5holidays5 \
libkf5i18n-data \
libkf5i18n5 \
libkf5iconthemes-bin \
libkf5iconthemes-data \
libkf5iconthemes5 \
libkf5identitymanagement5 \
libkf5idletime5 \
libkf5imap5 \
libkf5incidenceeditor-bin \
libkf5incidenceeditor5 \
libkf5itemmodels5 \
libkf5itemviews-data \
libkf5itemviews5 \
libkf5jobwidgets-data \
libkf5jobwidgets5 \
libkf5js5 \
libkf5jsembed-data \
libkf5jsembed5 \
libkf5kaddressbookgrantlee5 \
libkf5kcmutils-data \
libkf5kcmutils5 \
libkf5kdcraw5 \
libkf5kdelibs4support-data \
libkf5kdelibs4support5 \
libkf5kdelibs4support5-bin \
libkf5kdepimdbusinterfaces5 \
libkf5kdgantt2-5 \
libkf5khtml-bin \
libkf5khtml-data \
libkf5khtml5 \
libkf5kiocore5 \
libkf5kiofilewidgets5 \
libkf5kiogui5 \
libkf5kiontlm5 \
libkf5kiowidgets5 \
libkf5kipi-data \
libkf5kipi31.0.0 \
libkf5kmanagesieve5 \
libkf5kontactinterface-data \
libkf5kontactinterface5 \
libkf5krosscore5 \
libkf5krossui5 \
libkf5ksieve-data \
libkf5ksieve5 \
libkf5ksieveui5 \
libkf5ldap5 \
libkf5libkdepim-data \
libkf5libkdepim-plugins \
libkf5libkdepim5 \
libkf5libkleo5 \
libkf5mailcommon-plugins \
libkf5mailcommon5 \
libkf5mailimporter5 \
libkf5mailtransport-data \
libkf5mailtransport5 \
libkf5mbox5 \
libkf5messagecomposer5 \
libkf5messagecore5 \
libkf5messagelist5 \
libkf5messageviewer5 \
libkf5mime5 \
libkf5modemmanagerqt6 \
libkf5networkmanagerqt6 \
libkf5newstuff-data \
libkf5newstuff5 \
libkf5notifications-data \
libkf5notifications5 \
libkf5notifyconfig-data \
libkf5notifyconfig5 \
libkf5package-data \
libkf5package5 \
libkf5parts-data \
libkf5parts-plugins \
libkf5parts5 \
libkf5people-data \
libkf5people5 \
libkf5peoplebackend5 \
libkf5peoplewidgets5 \
libkf5pimcommon-plugins \
libkf5pimcommon5 \
libkf5pimtextedit5 \
libkf5plasma5 \
libkf5plasmaquick5 \
libkf5pty-data \
libkf5pty5 \
libkf5purpose-bin \
libkf5purpose5 \
libkf5qgpgme5 \
libkf5quickaddons5 \
libkf5runner5 \
libkf5screen-bin \
libkf5screen7 \
libkf5sendlater5 \
libkf5service-bin \
libkf5service-data \
libkf5service5 \
libkf5solid5 \
libkf5solid5-data \
libkf5sonnet5-data \
libkf5sonnetcore5 \
libkf5sonnetui5 \
libkf5style5 \
libkf5su-bin \
libkf5su-data \
libkf5su5 \
libkf5syndication5 \
libkf5sysguard-bin \
libkf5sysguard-data \
libkf5templateparser5 \
libkf5texteditor5 \
libkf5textwidgets-data \
libkf5textwidgets5 \
libkf5threadweaver5 \
libkf5tnef5 \
libkf5unitconversion-data \
libkf5unitconversion5 \
libkf5wallet-bin \
libkf5wallet-data \
libkf5wallet5 \
libkf5waylandclient5 \
libkf5waylandserver5 \
libkf5webkit5 \
libkf5widgetsaddons-data \
libkf5widgetsaddons5 \
libkf5windowsystem-data \
libkf5windowsystem5 \
libkf5xmlgui-bin \
libkf5xmlgui-data \
libkf5xmlgui5 \
libkf5xmlrpcclient-data \
libkf5xmlrpcclient5 \
libkfile4 \
libkfontinst5 \
libkfontinstui5 \
libkhtml5 \
libkio5 \
libkjsapi4 \
libkjsembed4 \
libkldap4 \
libklibc \
libkmediaplayer4 \
libkmime4 \
libkmod2 \
libknewstuff2-4 \
libknewstuff3-4 \
libknotifyconfig4 \
libkntlm4 \
libkolab1 \
libkolabxml1v5 \
libkonq-common \
libkonq5-templates \
libkonq5abi1 \
libkonqsidebarplugin4a \
libkopete4 \
libkparts4 \
libkpathsea6 \
libkpimidentities4 \
libkpimtextedit4 \
libkpimutils4 \
libkprintutils4 \
libkpty4 \
libkrb5-3 \
libkrb5support0 \
libkresources4 \
libkrosscore4 \
libksba8 \
libkscreenlocker5 \
libksgrd7 \
libksignalplotter7 \
libktexteditor4 \
libkwalletbackend5-5 \
libkwin4-effect-builtins1 \
libkwineffects9 \
libkwinglutils9 \
libkwinxrenderutils9 \
libkworkspace5-5 \
libkxmlrpcclient4 \
libkyotocabinet16v5 \
liblangtag-common \
liblangtag1 \
liblapack3 \
liblayout-java \
liblcms2-2 \
liblcms2-utils \
libldap-2.4-2 \
libldap-common \
libldb1 \
libldm-1.0-0 \
liblibreofficekitgtk \
liblilv-0-0 \
liblimba0 \
liblirc-client0 \
liblist-moreutils-perl \
liblivemedia57 \
libllvm3.8 \
libllvm3.9 \
liblmdb0 \
liblnk1 \
libloader-java \
liblocale-gettext-perl \
liblockfile-bin \
liblog-message-perl \
liblog-message-simple-perl \
liblog4j1.2-java \
liblogging-stdlog0 \
liblognorm5 \
liblouis-data \
liblouis12 \
liblouisutdml-bin \
liblouisutdml-data \
liblouisutdml7 \
liblqr-1-0 \
liblsan0 \
libltdl-dev \
libltdl7 \
liblua5.1-0 \
liblua5.2-0 \
liblua5.3-0 \
liblvm2app2.2 \
liblvm2cmd2.02 \
liblwp-mediatypes-perl \
liblwp-protocol-https-perl \
liblwres141 \
liblz4-1 \
liblzma5 \
liblzo2-2 \
libmad0 \
libmagic-mgc \
libmagic1 \
libmagick++-6.q16-7 \
libmagickcore-6.q16-3 \
libmagickcore-6.q16-3-extra \
libmagickwand-6.q16-3 \
libmail-java \
libmailtools-perl \
libmailutils5 \
libmariadbclient18 \
libmatroska6v5 \
libmbedcrypto0 \
libmbim-glib4 \
libmbim-proxy \
libmcrypt4 \
libmeanwhile1 \
libmediaart-2.0-0 \
libmediastreamer-base3 \
libmetis5 \
libmhash2 \
libmicrodns0 \
libminiupnpc10 \
libmission-control-plugins0 \
libmjpegutils-2.1-0 \
libmm-glib0 \
libmms0 \
libmng1 \
libmnl0 \
libmodplug1 \
libmono-corlib4.5-cil \
libmono-i18n-west4.0-cil \
libmono-i18n4.0-cil \
libmono-posix4.0-cil \
libmono-security4.0-cil \
libmono-system-configuration4.0-cil \
libmono-system-core4.0-cil \
libmono-system-security4.0-cil \
libmono-system-xml4.0-cil \
libmono-system4.0-cil \
libmount1 \
libmozjs-24-0 \
libmp3lame0 \
libmpc3 \
libmpcdec6 \
libmpdec2 \
libmpeg2-4 \
libmpeg2encpp-2.1-0 \
libmpfr4 \
libmpg123-0 \
libmplex2-2.1-0 \
libmpx2 \
libmsiecf1 \
libmspack0 \
libmspub-0.1-1 \
libmsv-java \
libmtdev1 \
libmtp-common \
libmtp-runtime \
libmtp9 \
libmusicbrainz5-2 \
libmusicbrainz5cc2v5 \
libmutter0i \
libmwaw-0.3-3 \
libmythes-1.2-0 \
libnatpmp1 \
libnautilus-extension1a \
libncurses5 \
libncurses5-dev \
libncursesw5 \
libndp0 \
libneon27-gnutls \
libnepomuk4 \
libnepomukquery4a \
libnepomukutils4 \
libnet-dbus-perl \
libnet-domain-tld-perl \
libnet-http-perl \
libnet-ipv6addr-perl \
libnet-netmask-perl \
libnet-smtp-ssl-perl \
libnet-ssleay-perl \
libnetaddr-ip-perl \
libnetcf1 \
libnetfilter-conntrack3 \
libnetpbm10 \
libnettle6 \
libnetwork-ipv4addr-perl \
libnewt0.52 \
libnfnetlink0 \
libnfs8 \
libnghttp2-14 \
libnl-3-200 \
libnl-3-dev \
libnl-genl-3-200 \
libnl-route-3-200 \
libnl-route-3-dev \
libnm-glib4 \
libnm-gtk0 \
libnm-util2 \
libnm0 \
libnma0 \
libnotify4 \
libnpth0 \
libnspr4 \
libnss-libvirt \
libnss-mdns \
libnss-myhostname \
libnss3 \
libntfs-3g871 \
libntlm0 \
libntlm0-dev \
libntrack-qt4-1 \
libntrack0 \
libnuma1 \
liboauth0 \
libobjc4 \
libodfgen-0.1-1 \
libofa0 \
libogg0 \
libokularcore7 \
libolecf1 \
libopenal-data \
libopenal1 \
libopenconnect5 \
libopencore-amrnb0 \
libopencore-amrwb0 \
libopencv-calib3d2.4v5 \
libopencv-core2.4v5 \
libopencv-features2d2.4v5 \
libopencv-flann2.4v5 \
libopencv-highgui2.4-deb0 \
libopencv-imgproc2.4v5 \
libopencv-objdetect2.4v5 \
libopencv-video2.4v5 \
libopenexr22 \
libopenjp2-7 \
libopenmpt-modplug1 \
libopenmpt0 \
libopus0 \
liborc-0.4-0 \
liborcus-0.11-0 \
libortp9 \
libosinfo-1.0-0 \
libosinfo-bin \
libotr5 \
libout123-0 \
liboxygenstyle5-5 \
liboxygenstyleconfig5-5 \
libp11-kit-dev \
libp11-kit0 \
libpackagekit-glib2-18 \
libpackagekitqt5-0 \
libpagemaker-0.0-0 \
libpam-cap \
libpam-gnome-keyring \
libpam-kwallet-common \
libpam-kwallet5 \
libpam-modules \
libpam-modules-bin \
libpam-runtime \
libpam-systemd \
libpam0g \
libpanel-applet0 \
libpango-1.0-0 \
libpango-perl \
libpangocairo-1.0-0 \
libpangoft2-1.0-0 \
libpangomm-1.4-1v5 \
libpangoxft-1.0-0 \
libpaper-utils \
libpaper1 \
libparted2 \
libpcap0.8 \
libpcaudio0 \
libpci-dev \
libpci3 \
libpciaccess-dev \
libpciaccess0 \
libpcre16-3 \
libpcre2-8-0 \
libpcre3 \
libpcre3-dev \
libpcre32-3 \
libpcrecpp0v5 \
libpcsclite1 \
libpeas-1.0-0 \
libpeas-common \
libpentaho-reporting-flow-engine-java \
libperl4-corelibs-perl \
libperl5.24 \
libpff1 \
libpgm-5.2-0 \
libphodav-2.0-0 \
libphodav-2.0-common \
libphonenumber7 \
libphonon4 \
libphonon4qt5-4 \
libpipeline1 \
libpixie-java \
libpixman-1-0 \
libpixman-1-dev \
libplasma-geolocation-interface5 \
libplasma3 \
libplist3 \
libpng-dev \
libpng-tools \
libpng16-16 \
libpolkit-agent-1-0 \
libpolkit-backend-1-0 \
libpolkit-gobject-1-0 \
libpolkit-qt-1-1 \
libpolkit-qt5-1-1 \
libpoppler-glib8 \
libpoppler-qt4-4 \
libpoppler-qt5-1 \
libpoppler64 \
libpopt0 \
libportaudio2 \
libpostproc54 \
libpotrace0 \
libpowerdevilcore2 \
libpowerdevilui5 \
libpq5 \
libprocesscore7 \
libprocessui7 \
libprocps6 \
libprotobuf-c1 \
libprotobuf-lite10 \
libprotobuf10 \
libproxy-tools \
libproxy1-plugin-gsettings \
libproxy1-plugin-networkmanager \
libproxy1v5 \
libpsl5 \
libpst4 \
libpthread-stubs0-dev \
libpulse-dev \
libpulse-mainloop-glib0 \
libpulse0 \
libpulsedsp \
libpwquality-common \
libpwquality1 \
libpython-dev \
libpython-stdlib \
libpython2.7 \
libpython2.7-dev \
libpython2.7-minimal \
libpython2.7-stdlib \
libpython3-stdlib \
libpython3.5 \
libpython3.5-minimal \
libpython3.5-stdlib \
libqaccessibilityclient0 \
libqalculate5-data \
libqalculate5v5 \
libqca-qt5-2 \
libqca-qt5-2-plugins \
libqca2 \
libqca2-plugin-ossl \
libqca2-plugins \
libqcow1 \
libqgsttools-p1 \
libqimageblitz4 \
libqmi-glib5 \
libqmi-proxy \
libqmobipocket1 \
libqpdf17 \
libqqwing2v5 \
libqt4-dbus \
libqt4-declarative \
libqt4-designer \
libqt4-network \
libqt4-opengl \
libqt4-qt3support \
libqt4-script \
libqt4-sql \
libqt4-sql-mysql \
libqt4-sql-sqlite \
libqt4-svg \
libqt4-xml \
libqt4-xmlpatterns \
libqt5clucene5 \
libqt5concurrent5 \
libqt5core5a \
libqt5dbus5 \
libqt5designer5 \
libqt5designercomponents5 \
libqt5gui5 \
libqt5help5 \
libqt5multimedia5 \
libqt5multimedia5-plugins \
libqt5multimediaquick-p5 \
libqt5multimediawidgets5 \
libqt5network5 \
libqt5opengl5 \
libqt5printsupport5 \
libqt5qml5 \
libqt5quick5 \
libqt5quickwidgets5 \
libqt5script5 \
libqt5sql5 \
libqt5sql5-mysql \
libqt5sql5-sqlite \
libqt5svg5 \
libqt5test5 \
libqt5webkit5 \
libqt5widgets5 \
libqt5x11extras5 \
libqt5xml5 \
libqt5xmlpatterns5 \
libqtcore4 \
libqtcurve-utils2 \
libqtdbus4 \
libqtgui4 \
libqtwebkit4 \
libquadmath0 \
libquvi-0.9-0.9.3 \
libquvi-scripts-0.9 \
librados2 \
libraptor2-0 \
librarian0 \
librasqal3 \
libraw1394-11 \
libraw15 \
librbd1 \
librdf0 \
libreadline-dev \
libreadline5 \
libreadline7 \
libregexp-assemble-perl \
libregf1 \
libregfi1 \
librelaxng-datatype-java \
libreoffice \
libreoffice-avmedia-backend-gstreamer \
libreoffice-base \
libreoffice-base-core \
libreoffice-base-drivers \
libreoffice-calc \
libreoffice-common \
libreoffice-core \
libreoffice-draw \
libreoffice-evolution \
libreoffice-gnome \
libreoffice-gtk3 \
libreoffice-help-en-us \
libreoffice-help-ja \
libreoffice-impress \
libreoffice-java-common \
libreoffice-kde \
libreoffice-l10n-ja \
libreoffice-librelogo \
libreoffice-math \
libreoffice-nlpsolver \
libreoffice-ogltrans \
libreoffice-pdfimport \
libreoffice-report-builder \
libreoffice-report-builder-bin \
libreoffice-script-provider-bsh \
libreoffice-script-provider-js \
libreoffice-script-provider-python \
libreoffice-sdbc-hsqldb \
libreoffice-sdbc-postgresql \
libreoffice-style-breeze \
libreoffice-style-galaxy \
libreoffice-style-tango \
libreoffice-wiki-publisher \
libreoffice-writer \
libreofficekit-data \
librepository-java \
libresid-builder0c2a \
librest-0.7-0 \
librevenge-0.0-0 \
librhythmbox-core10 \
librpm3 \
librpmbuild3 \
librpmio3 \
librpmsign3 \
librsvg2-2 \
librsvg2-common \
librte-acl2 \
librte-cfgfile2 \
librte-cmdline2 \
librte-cryptodev2 \
librte-distributor1 \
librte-eal3 \
librte-ethdev5 \
librte-hash2 \
librte-ip-frag1 \
librte-jobstats1 \
librte-kni2 \
librte-kvargs1 \
librte-lpm2 \
librte-mbuf2 \
librte-mempool2 \
librte-meter1 \
librte-net1 \
librte-pdump1 \
librte-pipeline3 \
librte-pmd-af-packet1 \
librte-pmd-bnxt1 \
librte-pmd-bond1 \
librte-pmd-cxgbe1 \
librte-pmd-e1000-1 \
librte-pmd-ena1 \
librte-pmd-enic1 \
librte-pmd-fm10k1 \
librte-pmd-i40e1 \
librte-pmd-ixgbe1 \
librte-pmd-null-crypto1 \
librte-pmd-null1 \
librte-pmd-pcap1 \
librte-pmd-qede1 \
librte-pmd-ring2 \
librte-pmd-vhost1 \
librte-pmd-virtio1 \
librte-pmd-vmxnet3-uio1 \
librte-pmd-xenvirt1 \
librte-port3 \
librte-power1 \
librte-reorder1 \
librte-ring1 \
librte-sched1 \
librte-table2 \
librte-timer1 \
librte-vhost3 \
librtmp1 \
librubberband2 \
libruby2.3 \
librygel-core-2.6-2 \
librygel-db-2.6-2 \
librygel-renderer-2.6-2 \
librygel-renderer-gst-2.6-2 \
librygel-server-2.6-2 \
libsac-java \
libsac-java-gcj \
libsamplerate0 \
libsane \
libsane-common \
libsane-extras \
libsane-extras-common \
libsane-hpaio \
libsanlock-client1 \
libsasl2-2 \
libsasl2-modules \
libsasl2-modules-db \
libsaxonhe-java \
libsbc1 \
libscca1 \
libscim8v5 \
libsdl-image1.2 \
libsdl1.2-dev \
libsdl1.2debian \
libseccomp2 \
libsecret-1-0 \
libsecret-common \
libselinux1 \
libselinux1-dev \
libsemanage-common \
libsemanage1 \
libsensors4 \
libsepol1 \
libsepol1-dev \
libserd-0-0 \
libserializer-java \
libservlet3.1-java \
libsgutils2-2 \
libshine3 \
libshout3 \
libsidplay1v5 \
libsidplay2 \
libsigc++-2.0-0v5 \
libsignon-plugins-common1 \
libsignon-qt5-1 \
libsigscan1 \
libsigsegv2 \
libslang2 \
libslang2-dev \
libsm6 \
libsmartcols1 \
libsmbclient \
libsmdev1 \
libsmraw1 \
libsnappy1v5 \
libsndfile1 \
libsndio6.1 \
libsnmp-base \
libsnmp30 \
libsocket6-perl \
libsodium18 \
libsolid4 \
libsonic0 \
libsoprano4 \
libsord-0-0 \
libsort-versions-perl \
libsoundtouch1 \
libsoup-gnome2.4-1 \
libsoup2.4-1 \
libsox-fmt-alsa \
libsox-fmt-base \
libsox2 \
libsoxr0 \
libspandsp2 \
libspectre1 \
libspeechd2 \
libspeex1 \
libspeexdsp1 \
libspice-client-glib-2.0-8 \
libspice-client-gtk-3.0-5 \
libspice-server1 \
libsqlite3-0 \
libsqlite3-dev \
libsratom-0-0 \
libsrtp0 \
libss2 \
libssh-4 \
libssh-gcrypt-4 \
libssh2-1 \
libssl-dev \
libssl-doc \
libssl1.0.2 \
libssl1.1 \
libstartup-notification0 \
libstdc++-6-dev \
libstdc++6 \
libstemmer0d \
libstoken1 \
libstring-shellquote-perl \
libsubunit-dev \
libsubunit0 \
libsuitesparseconfig4 \
libswitch-perl \
libswresample2 \
libswscale4 \
libsys-virt-perl \
libsystemd0 \
libtag1v5 \
libtag1v5-vanilla \
libtagc0 \
libtalloc2 \
libtaskmanager6 \
libtasn1-6 \
libtasn1-6-dev \
libtasn1-doc \
libtbb2 \
libtcl8.6 \
libtdb1 \
libteamdctl0 \
libtelepathy-glib0 \
libtelepathy-logger3 \
libterm-readkey-perl \
libterm-size-perl \
libterm-ui-perl \
libtevent0 \
libtext-charwidth-perl \
libtext-iconv-perl \
libtext-template-perl \
libtext-wrapi18n-perl \
libthai-data \
libthai0 \
libtheora0 \
libthreadweaver4 \
libtidy5 \
libtie-ixhash-perl \
libtiff5 \
libtimedate-perl \
libtinfo-dev \
libtinfo5 \
libtk8.6 \
libtomcrypt0 \
libtommath1 \
libtool \
libtotem-plparser-common \
libtotem-plparser18 \
libtotem0 \
libtracker-control-1.0-0 \
libtracker-miner-1.0-0 \
libtracker-sparql-1.0-0 \
libtsan0 \
libtsk13 \
libturbojpeg0 \
libtwolame0 \
libtxc-dxtn-s2tc \
libubsan0 \
libudev-dev \
libudev1 \
libudisks2-0 \
libuim-custom2 \
libuim-data \
libuim-plugins \
libuim-scm0 \
libuim8 \
libumfpack5 \
libunbound2 \
libunistring0 \
libupnp6 \
libupower-glib3 \
liburi-perl \
libusageenvironment3 \
libusb-0.1-4 \
libusb-1.0-0 \
libusbmuxd4 \
libusbredirhost1 \
libusbredirparser1 \
libustr-1.0-1 \
libutempter0 \
libuuid1 \
libuv1 \
libv4l-0 \
libv4lconvert0 \
libva-drm1 \
libva-wayland1 \
libva-x11-1 \
libva1 \
libvcdinfo0 \
libvdeplug2 \
libvdpau-va-gl1 \
libvdpau1 \
libvhdi1 \
libvirt-clients \
libvirt-daemon \
libvirt-daemon-system \
libvirt-dev \
libvirt-doc \
libvirt-glib-1.0-0 \
libvirt-sanlock \
libvirt0 \
libvisio-0.1-1 \
libvisual-0.4-0 \
libvlc-bin \
libvlc5 \
libvlccore9 \
libvmdk1 \
libvmime-dev \
libvmime0 \
libvncclient1 \
libvncserver-config \
libvncserver-dev \
libvncserver1 \
libvo-aacenc0 \
libvo-amrwbenc0 \
libvorbis0a \
libvorbisenc2 \
libvorbisfile3 \
libvpx4 \
libvshadow1 \
libvslvm1 \
libvte-2.91-0 \
libvte-2.91-common \
libvte-common \
libvte9 \
libwacom-bin \
libwacom-common \
libwacom2 \
libwavpack1 \
libwayland-client0 \
libwayland-cursor0 \
libwayland-egl1-mesa \
libwayland-server0 \
libwbclient0 \
libweather-ion7 \
libwebkit2gtk-4.0-37 \
libwebp6 \
libwebpdemux2 \
libwebpmux2 \
libwebrtc-audio-processing1 \
libwildmidi-config \
libwildmidi2 \
libwin-hivex-perl \
libwinpr-crt0.1 \
libwinpr-crypto0.1 \
libwinpr-dsparse0.1 \
libwinpr-environment0.1 \
libwinpr-file0.1 \
libwinpr-handle0.1 \
libwinpr-heap0.1 \
libwinpr-input0.1 \
libwinpr-interlocked0.1 \
libwinpr-library0.1 \
libwinpr-path0.1 \
libwinpr-pool0.1 \
libwinpr-registry0.1 \
libwinpr-rpc0.1 \
libwinpr-sspi0.1 \
libwinpr-synch0.1 \
libwinpr-sysinfo0.1 \
libwinpr-thread0.1 \
libwinpr-utils0.1 \
libwmf-bin \
libwmf0.2-7 \
libwnck-3-0 \
libwnck-3-common \
libwpd-0.10-10 \
libwpg-0.3-3 \
libwps-0.4-4 \
libwrap0 \
libwww-perl \
libwww-robotrules-perl \
libx11-6 \
libx11-data \
libx11-dev \
libx11-doc \
libx11-protocol-perl \
libx11-xcb-dev \
libx11-xcb1 \
libx264-148 \
libx265-95 \
libx32asan3 \
libx32atomic1 \
libx32cilkrts5 \
libx32gcc-6-dev \
libx32gcc1 \
libx32gomp1 \
libx32itm1 \
libx32quadmath0 \
libx32stdc++6 \
libx32ubsan0 \
libx86-1 \
libxapian30 \
libxatracker2 \
libxau-dev \
libxau6 \
libxaw7 \
libxc-dev \
libxc4 \
libxcb-composite0 \
libxcb-cursor0 \
libxcb-damage0 \
libxcb-dpms0 \
libxcb-dri2-0 \
libxcb-dri2-0-dev \
libxcb-dri3-0 \
libxcb-dri3-dev \
libxcb-glx0 \
libxcb-glx0-dev \
libxcb-icccm4 \
libxcb-image0 \
libxcb-keysyms1 \
libxcb-present-dev \
libxcb-present0 \
libxcb-randr0 \
libxcb-randr0-dev \
libxcb-record0 \
libxcb-render-util0 \
libxcb-render0 \
libxcb-render0-dev \
libxcb-res0 \
libxcb-shape0 \
libxcb-shape0-dev \
libxcb-shm0 \
libxcb-sync-dev \
libxcb-sync1 \
libxcb-util0 \
libxcb-xf86dri0 \
libxcb-xfixes0 \
libxcb-xfixes0-dev \
libxcb-xinerama0 \
libxcb-xkb1 \
libxcb-xv0 \
libxcb1 \
libxcb1-dev \
libxcomposite1 \
libxcursor1 \
libxdamage-dev \
libxdamage1 \
libxdmcp-dev \
libxdmcp6 \
libxen-4.8 \
libxen-dev \
libxenstore3.0 \
libxerces-c3.1 \
libxerces2-java \
libxext-dev \
libxext6 \
libxfixes-dev \
libxfixes3 \
libxfont1 \
libxfont2 \
libxft2 \
libxi6 \
libxinerama1 \
libxkbcommon-x11-0 \
libxkbcommon0 \
libxkbfile1 \
libxklavier16 \
libxml-commons-external-java \
libxml-commons-resolver1.1-java \
libxml-java \
libxml-parser-perl \
libxml-twig-perl \
libxml-xpath-perl \
libxml-xpathengine-perl \
libxml2 \
libxml2-dev \
libxml2-utils \
libxmlbeans-java \
libxmu6 \
libxmuu1 \
libxom-java \
libxpm4 \
libxpp2-java \
libxpp3-java \
libxrandr2 \
libxrender1 \
libxres1 \
libxshmfence-dev \
libxshmfence1 \
libxslt1.1 \
libxss1 \
libxt6 \
libxtables12 \
libxtst6 \
libxv1 \
libxvidcore4 \
libxvmc1 \
libxxf86dga1 \
libxxf86vm-dev \
libxxf86vm1 \
libyajl-dev \
libyajl2 \
libyaml-0-2 \
libyaml-dev \
libyara3 \
libyelp0 \
libytnef0 \
libzapojit-0.0-0 \
libzbar0 \
libzeitgeist-2.0-0 \
libzinnia0 \
libzip4 \
libzmq5 \
libzvbi-common \
libzvbi0 \
lightning \
lightsoff \
lime-forensics-dkms \
linux-base \
linux-compiler-gcc-6-x86 \
linux-headers-4.9.0-6-amd64 \
linux-headers-4.9.0-6-common \
linux-headers-amd64 \
linux-image-4.9.0-6-amd64 \
linux-image-amd64 \
linux-kbuild-4.9 \
linux-libc-dev \
llvm \
llvm-3.8 \
llvm-3.8-dev \
llvm-3.8-runtime \
llvm-dev \
llvm-runtime \
locales \
login \
logrotate \
lp-solve \
lsb-base \
lsb-release \
lsof \
lsscsi \
lua-bitop \
lua-expat \
lua-json \
lua-lpeg \
lua-socket \
lv \
lvm2 \
lzop \
m4 \
mac-robber \
magicrescue \
mailutils \
mailutils-common \
make \
man-db \
manpages \
manpages-dev \
manpages-ja \
manpages-ja-dev \
mariadb-client-10.1 \
mariadb-client-core-10.1 \
mariadb-common \
mariadb-server-10.1 \
mariadb-server-core-10.1 \
mawk \
mdadm \
media-player-info \
memdump \
mesa-common-dev \
mesa-utils \
mesa-va-drivers \
mesa-vdpau-drivers \
metacam \
milou \
mime-support \
minissdpd \
missidentify \
mobile-broadband-provider-info \
modemmanager \
module-assistant \
mono-4.0-gac \
mono-gac \
mono-runtime \
mono-runtime-common \
mono-runtime-sgen \
mount \
mousetweaks \
mozc-data \
mozc-server \
mozc-utils-gui \
mpg123 \
mscompress \
mtools \
multiarch-support \
mutter \
mutter-common \
myrescue \
mysql-common \
mysql-server \
mythes-en-us \
nano \
nasty \
nautilus \
nautilus-data \
nautilus-sendto \
ncurses-base \
ncurses-bin \
ncurses-term \
net-tools \
netbase \
netcat-openbsd \
netcat-traditional \
netpbm \
nettle-dev \
network-manager \
network-manager-gnome \
nkf \
nodejs \
notification-daemon \
ntfs-3g \
ntrack-module-libnl-0 \
ocaml \
ocaml-base \
ocaml-base-nox \
ocaml-compiler-libs \
ocaml-findlib \
ocaml-interp \
ocaml-nox \
okular \
openbios-ppc \
openbios-sparc \
openhackware \
openjdk-8-jre \
openjdk-8-jre-headless \
openprinting-ppds \
openssh-client \
openssh-server \
openssh-sftp-server \
openssl \
os-prober \
osinfo-db \
outguess \
oxygen-icon-theme \
oxygen-sounds \
p11-kit \
p11-kit-modules \
p7zip \
p7zip-full \
packagekit \
packagekit-tools \
parted \
pasco \
passwd \
patch \
pciutils \
perl \
perl-base \
perl-modules-5.24 \
perl-openssl-defaults \
pff-tools \
phonon \
phonon-backend-gstreamer \
phonon-backend-gstreamer-common \
phonon4qt5 \
phonon4qt5-backend-vlc \
pinentry-curses \
pinentry-gnome3 \
pipebench \
pkg-config \
plasma-dataengines-addons \
plasma-desktop \
plasma-desktop-data \
plasma-discover \
plasma-discover-common \
plasma-framework \
plasma-integration \
plasma-nm \
plasma-pa \
plasma-runners-addons \
plasma-scriptengine-javascript \
plasma-wallpapers-addons \
plasma-widgets-addons \
plasma-workspace \
plaso \
pm-utils \
polari \
policykit-1 \
polkit-kde-1 \
polkit-kde-agent-1 \
pompem \
poppler-data \
poppler-utils \
powerdevil \
powerdevil-data \
powermgmt-base \
powertop \
ppp \
printer-driver-all \
printer-driver-brlaser \
printer-driver-c2050 \
printer-driver-c2esp \
printer-driver-cjet \
printer-driver-dymo \
printer-driver-escpr \
printer-driver-foo2zjs \
printer-driver-foo2zjs-common \
printer-driver-fujixerox \
printer-driver-gutenprint \
printer-driver-hpcups \
printer-driver-hpijs \
printer-driver-m2300w \
printer-driver-min12xxw \
printer-driver-pnm2ppa \
printer-driver-postscript-hp \
printer-driver-ptouch \
printer-driver-pxljr \
printer-driver-sag-gdi \
printer-driver-splix \
procps \
psf-unifont \
psmisc \
pulseaudio \
pulseaudio-module-bluetooth \
pulseaudio-module-gconf \
pulseaudio-utils \
python \
python-acora \
python-aff4 \
python-apt-common \
python-arrow \
python-artifacts \
python-attr \
python-backports-shutil-get-terminal-size \
python-binplist \
python-bittorrent \
python-bs4 \
python-cairo \
python-capstone \
python-cffi-backend \
python-chardet \
python-click \
python-colorama \
python-configparser \
python-constantly \
python-construct \
python-crypto \
python-cryptography \
python-dateutil \
python-dbus \
python-decorator \
python-dev \
python-dfdatetime \
python-dfvfs \
python-dfwinreg \
python-distorm3 \
python-dpkt \
python-dumbnet \
python-efilter \
python-enum34 \
python-future \
python-gconf \
python-gevent \
python-gi \
python-gi-cairo \
python-glade2 \
python-gobject-2 \
python-greenlet \
python-gtk2 \
python-hachoir-core \
python-hachoir-metadata \
python-hachoir-parser \
python-html5lib \
python-idna \
python-imaging \
python-incremental \
python-intervaltree \
python-ipaddr \
python-ipaddress \
python-ipython \
python-ipython-genutils \
python-isodate \
python-jdcal \
python-keybinder \
python-libbde \
python-libesedb \
python-libevt \
python-libevtx \
python-libewf \
python-libfsntfs \
python-libfvde \
python-libfwnt \
python-libfwsi \
python-liblnk \
python-libmsiecf \
python-libolecf \
python-libqcow \
python-libregf \
python-libscca \
python-libsigscan \
python-libsmdev \
python-libsmraw \
python-libvhdi \
python-libvirt \
python-libvmdk \
python-libvshadow \
python-libvslvm \
python-libxml2 \
python-lxml \
python-minimal \
python-notify \
python-numpy \
python-openpyxl \
python-openssl \
python-pam \
python-pathlib2 \
python-pefile \
python-pexpect \
python-pickleshare \
python-pil \
python-pkg-resources \
python-prompt-toolkit \
python-protobuf \
python-psutil \
python-ptyprocess \
python-py \
python-pyasn1 \
python-pyasn1-modules \
python-pyelftools \
python-pygments \
python-pyparsing \
python-pytest \
python-rdflib \
python-rekall-core \
python-requests \
python-scour \
python-serial \
python-service-identity \
python-setuptools \
python-simplegeneric \
python-six \
python-sortedcontainers \
python-sparqlwrapper \
python-talloc \
python-traitlets \
python-tsk \
python-twisted \
python-twisted-bin \
python-twisted-core \
python-tz \
python-urllib3 \
python-vte \
python-wcwidth \
python-webencodings \
python-xdg \
python-xlsxwriter \
python-yaml \
python-yara \
python-zmq \
python-zope.interface \
python2.7 \
python2.7-dev \
python2.7-minimal \
python3 \
python3-apt \
python3-botocore \
python3-brlapi \
python3-cairo \
python3-chardet \
python3-colorama \
python3-cups \
python3-cupshelpers \
python3-dateutil \
python3-dbus \
python3-debian \
python3-debianbts \
python3-docutils \
python3-gi \
python3-gi-cairo \
python3-httplib2 \
python3-jmespath \
python3-louis \
python3-mako \
python3-markupsafe \
python3-minimal \
python3-pexpect \
python3-pil \
python3-pkg-resources \
python3-ptyprocess \
python3-pyasn1 \
python3-pyatspi \
python3-pycurl \
python3-pygments \
python3-pyqt5 \
python3-pysimplesoap \
python3-renderpm \
python3-reportbug \
python3-reportlab \
python3-reportlab-accel \
python3-requests \
python3-roman \
python3-rsa \
python3-s3transfer \
python3-sip \
python3-six \
python3-smbc \
python3-software-properties \
python3-speechd \
python3-uno \
python3-urllib3 \
python3-xdg \
python3.5 \
python3.5-minimal \
qdbus \
qdbus-qt5 \
qemu \
qemu-efi \
qemu-kvm \
qemu-slof \
qemu-system \
qemu-system-arm \
qemu-system-common \
qemu-system-mips \
qemu-system-misc \
qemu-system-ppc \
qemu-system-sparc \
qemu-system-x86 \
qemu-user \
qemu-user-binfmt \
qemu-utils \
qml-module-org-kde-activities \
qml-module-org-kde-bluezqt \
qml-module-org-kde-draganddrop \
qml-module-org-kde-extensionplugin \
qml-module-org-kde-kcoreaddons \
qml-module-org-kde-kholidays \
qml-module-org-kde-kio \
qml-module-org-kde-kirigami \
qml-module-org-kde-kquickcontrols \
qml-module-org-kde-kquickcontrolsaddons \
qml-module-org-kde-kwindowsystem \
qml-module-org-kde-purpose \
qml-module-org-kde-runnermodel \
qml-module-org-kde-solid \
qml-module-qt-labs-folderlistmodel \
qml-module-qt-labs-settings \
qml-module-qtgraphicaleffects \
qml-module-qtmultimedia \
qml-module-qtqml-models2 \
qml-module-qtquick-controls \
qml-module-qtquick-controls-styles-breeze \
qml-module-qtquick-dialogs \
qml-module-qtquick-layouts \
qml-module-qtquick-privatewidgets \
qml-module-qtquick-window2 \
qml-module-qtquick2 \
qml-module-qtwebkit \
qpdf \
qt-at-spi \
qt5-gtk-platformtheme \
qt5-image-formats-plugins \
qtchooser \
qtcore4-l10n \
qttools5-dev-tools \
qttranslations5-l10n \
quadrapassel \
rake \
rarian-compat \
rbenv \
readline-common \
realmd \
recoverdm \
recoverjpeg \
reglookup \
reiserfsprogs \
rekall-core \
rename \
rephrase \
reportbug \
rhythmbox \
rhythmbox-data \
rhythmbox-plugin-cdrecorder \
rhythmbox-plugins \
rifiuti \
rifiuti2 \
rinse \
rkhunter \
rpm \
rpm-common \
rpm2cpio \
rsakeyfind \
rsync \
rsyslog \
rtkit \
ruby \
ruby-did-you-mean \
ruby-mime \
ruby-mime-types \
ruby-mini-exiftool \
ruby-minitest \
ruby-net-http-digest-auth \
ruby-net-telnet \
ruby-nokogiri \
ruby-pkg-config \
ruby-power-assert \
ruby-spider \
ruby-test-unit \
ruby-zip \
ruby2.3 \
rubygems-integration \
rygel \
rygel-playbin \
rygel-tracker \
safecopy \
samba-libs \
sane-utils \
scalpel \
scrounge-ntfs \
scrub \
sddm \
sddm-theme-debian-maui \
seabios \
seahorse \
seahorse-daemon \
sed \
sensible-utils \
sgabios \
sgml-base \
sgml-data \
shared-mime-info \
shed \
shotwell \
shotwell-common \
signon-plugin-oauth2 \
simple-scan \
sleuthkit \
smartmontools \
sni-qt \
socat \
software-properties-common \
software-properties-gtk \
software-properties-kde \
sonnet-plugins \
soprano-daemon \
sound-icons \
sound-theme-freedesktop \
sox \
speech-dispatcher \
speech-dispatcher-audio-plugins \
speech-dispatcher-espeak-ng \
speech-dispatcher-festival \
spice-client-glib-usb-acl-helper \
sqlite3 \
ssdeep \
ssh \
sshfs \
ssl-cert \
steghide \
sudo \
supermin \
sweeper \
swell-foop \
synaptic \
syslinux \
syslinux-common \
system-config-printer \
system-config-printer-common \
system-config-printer-udev \
systemd \
systemd-sysv \
systemsettings \
sysvinit-utils \
tableau-parm \
tali \
tar \
task-desktop \
task-gnome-desktop \
task-japanese \
task-japanese-desktop \
task-japanese-gnome-desktop \
task-kde-desktop \
task-laptop \
task-print-server \
task-ssh-server \
tasksel \
tasksel-data \
tcl \
tcl8.6 \
tcpd \
tegaki-zinnia-japanese \
telepathy-idle \
telepathy-logger \
telepathy-mission-control-5 \
telnet \
thunderbird \
thunderbird-l10n-ja \
tk \
tk8.6 \
totem \
totem-common \
totem-plugins \
traceroute \
tracker \
tracker-extract \
tracker-gui \
tracker-miner-fs \
transfig \
transmission-common \
transmission-gtk \
tree \
ttf-unifont \
tzdata \
ubuntu-archive-keyring \
ucf \
udev \
udisks2 \
uim \
uim-anthy \
uim-applet-gnome \
uim-common \
uim-fep \
uim-gtk2.0 \
uim-gtk3 \
uim-mozc \
uim-qt \
uim-qt5 \
uim-utils \
uim-xim \
unar \
unattended-upgrades \
undbx \
unhide \
unhide.rb \
unifont \
uno-libs3 \
unoconv \
unzip \
update-inetd \
upower \
ure \
usb-modeswitch \
usb-modeswitch-data \
usbmuxd \
usbutils \
user-manager \
util-linux \
uuid-dev \
va-driver-all \
vbetool \
vcdimager \
vdpau-driver-all \
vim \
vim-common \
vim-runtime \
vim-tiny \
vinagre \
vinetto \
vino \
virt-manager \
virt-top \
virt-viewer \
virtinst \
vlc-data \
vlc-plugin-base \
vlc-plugin-video-output \
volatility \
volatility-tools \
wamerican \
wget \
whiptail \
winregfs \
wipe \
wireless-regdb \
wireless-tools \
wodim \
wpasupplicant \
x11-apps \
x11-common \
x11-session-utils \
x11-utils \
x11-xkb-utils \
x11-xserver-utils \
x11proto-core-dev \
x11proto-damage-dev \
x11proto-dri2-dev \
x11proto-fixes-dev \
x11proto-gl-dev \
x11proto-input-dev \
x11proto-kb-dev \
x11proto-xext-dev \
x11proto-xf86vidmode-dev \
xauth \
xbitmaps \
xbrlapi \
xdg-user-dirs \
xdg-user-dirs-gtk \
xdg-utils \
xen-hypervisor-4.8-amd64 \
xen-linux-system-amd64 \
xen-system-amd64 \
xen-tools \
xen-utils-4.8 \
xen-utils-common \
xenstore-utils \
xenwatch \
xfonts-100dpi \
xfonts-75dpi \
xfonts-base \
xfonts-encodings \
xfonts-scalable \
xfonts-unifont \
xfonts-utils \
xfsprogs \
xinit \
xkb-data \
xml-core \
xorg \
xorg-docs-core \
xorg-sgml-doctools \
xserver-common \
xserver-xephyr \
xserver-xorg \
xserver-xorg-core \
xserver-xorg-input-all \
xserver-xorg-input-libinput \
xserver-xorg-input-wacom \
xserver-xorg-legacy \
xserver-xorg-video-all \
xserver-xorg-video-amdgpu \
xserver-xorg-video-ati \
xserver-xorg-video-fbdev \
xserver-xorg-video-intel \
xserver-xorg-video-nouveau \
xserver-xorg-video-qxl \
xserver-xorg-video-radeon \
xserver-xorg-video-vesa \
xserver-xorg-video-vmware \
xterm \
xtrans-dev \
xwayland \
xxd \
xz-utils \
yara \
yelp \
yelp-xsl \
zeitgeist-core \
zenity \
zenity-common \
zerofree \
zip \
zlib1g \
zlib1g-dev \
zsh \
zsh-common
