13xforever.language-x86-64-assembly
2gua.rainbow-brackets
aaron-bond.better-comments
ajshort.latex-preview
akamud.vscode-theme-onedark
attilabuti.brainfuck-syntax
austin.code-gnu-global
azemoh.one-monokai
azemoh.theme-onedark
bajdzis.vscode-database
basdp.language-gas-x86
bitlang.cobol
bung87.rails
bung87.vscode-gemfile
chenxsan.vscode-standardjs
CoenraadS.bracket-pair-colorizer
dakshmiglani.hex-to-rgba
DavidAnson.vscode-markdownlint
davidhouchin.whitespace-plus
donjayamanne.githistory
dracula-theme.theme-dracula
dunstontc.dark-plus-syntax
eamodio.gitlens
eg2.vscode-npm-script
emmanuelbeziat.vscode-great-icons
Equinusocio.vsc-material-theme
eriklynd.json-tools
felipecaputo.git-project-manager
felixfbecker.php-debug
felixfbecker.php-intellisense
formulahendry.auto-close-tag
formulahendry.code-runner
gccfeli.vscode-lua
gerane.Theme-azure
glen-84.sass-lint
HookyQR.beautify
Hridoy.rails-snippets
huizhou.githd
HvyIndustries.crane
idleberg.hopscotch
idleberg.nsis
ikappas.phpcs
itryapitsin.Scala
James-Yu.latex-workshop
jbenden.c-cpp-flylint
jchannon.csharpextensions
jinmingjian.sde
johnpapa.winteriscoming
justusadam.language-haskell
k--kato.docomment
Kasik96.swift
kdarkhan.mips
keroc.hex-fmt
kokororin.vscode-phpfmt
leizongmin.node-module-intellisense
Leopotam.csharpfixformat
linyang95.php-symbols
lkytal.FlatUI
mathiasfrohlich.Kotlin
mattn.Lisp
mikegleasonjr.theme-go
mitaki28.vscode-clang
MS-CEINTL.vscode-language-pack-ja
ms-mssql.mssql
ms-python.python
ms-vscode.cpptools
ms-vscode.csharp
ms-vscode.Go
ms-vscode.sublime-keybindings
ms-vscode.Theme-MarkdownKit
ms-vsts.team
mshr-h.veriloghdl
Nuuf.theme-hackershaze
p1c2u.docker-compose
pawelgrzybek.bimbo-theme
PeterJausovec.vscode-docker
phoityne.phoityne-vscode
PKief.material-icon-theme
rebornix.ruby
redhat.java
rintoj.blank-line-organizer
rlovelett.vscode-swift-language
robertohuertasm.vscode-icons
satokaz.vscode-bs-ctrlchar-remover
shanoor.vscode-nginx
shd101wyy.markdown-preview-enhanced
slevesque.vscode-hexdump
SolarLiner.linux-themes
Stephanvs.dot
tht13.python
vangware.dark-plus-material
vscjava.vscode-java-debug
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
whizkydee.material-palenight-theme
xabikos.JavaScriptSnippets
xaver.clang-format
yzhang.markdown-all-in-one
zaynyatyi.hexmachina-generator
zhuangtongfa.Material-theme
zxh404.vscode-proto3
